### PR TITLE
assets cleanup

### PR DESCRIPTION
**Pull request by DavidBadura**
* [x] remove bower
* [x] remove compass
* [x] add shortcuts
* [x] update readme
* [x] fix sementic themes
* [x] move `packages.json` and `gulp.js` into root folder

### CODE REVIEW

**Comment by DavidBadura** [comment]
ref #97

**Comment by DavidBadura** [comment]
@simpspector/owners ready :-)

**Comment by tolry** [comment]
:+1:

**Comment by larsborn** [comment]
+1 +1 +1!

**Comment by tolry** [comment]
Did you just merge your own PR? tsts ... :wink:

**Comment by larsborn** [comment]
wasn't this policy? We really need this COC.

**Comment by tolry** [comment]
yes we do, somebody volunteered writing it - I have to check that ;-)

**Pull request merged**
