### PR TITLE
space at top and logo spacing

### LINKED ISSUE #149: UI: insert space between first row and top of html-document

### PR DESCRIPTION
**Pull request by larsborn**
fixes #149

### CODE REVIEW

**Comment by DavidBadura** [comment]
:+1:

**Comment by larsborn** [comment]
I replaced all the px by em. I'd still keep the !important since afaik this is exactly the use case for it.

@tolry do I get a +1 from you? :)

**Comment by larsborn** [comment]
rebased.

**Comment by DavidBadura** [comment]
:+1:

**Comment by tolry** [comment]
I reeaheeally would like for this to work without the `!important` - really! Wouldn't a padding on the body be sufficient also? (no html to be altered)

**Comment by DavidBadura** [comment]
In this case it could be solved by adding a padding on the body. but we want a class to add a vertical spacing on all elements.

**Comment by larsborn** [comment]
ok let's solve the problem "how do we get a vertical spacing here" when we face it at more then one place. I now applied the padding to body.

**Comment by larsborn** [comment]
rebased.

**Comment by tolry** [comment]
Nice, I concurrently tried merging the PR :smile:

**Comment by tolry** [comment]
Thanks for compromising on this - those `!important` are kind of  a red flag to me :grin:

**Comment by DavidBadura** [comment]
a helper class can use the keyword `important`, a lot of libs do it so. And vertical-spacing was a halper class. But no matter...

**Pull request merged**
