### PR TITLE
App bundle refactoring

### LINKED ISSUE #17: rename service ids
prefix with simpspector instead of simplethings app

### PR DESCRIPTION
**Pull request by tolry**
fixes #17 

* first version
* should we prefix services with 'simpepsector.app' or just 'app'?

### CODE REVIEW

**Comment by DavidBadura** [comment]
:+1:

**Comment by tolry** [comment]
should be ready for review and merging @simpspector/owners - although it would be nice if someone could checkout the branch for themselves since there is lots of search replace magic happening here

**Comment by DavidBadura** [comment]
you have to update the path to the binaries.
https://github.com/simpspector/simpspector/blob/app-bundle-refactoring/src/AppBundle/AppBundle.php#L20

**Comment by DavidBadura** [comment]
if you change the path, everything works perfectly :+1:

**Comment by tolry** [comment]
@DavidBadura good catch, thanks - path is now adjusted

**Comment by dragonito** [comment]
+1

**Pull request merged**
