### PR TITLE
diff prototype

### PR DESCRIPTION
**Pull request by DavidBadura**
diff

### CODE REVIEW

**Comment by tolry** [comment]
:+1:  this will be a huge step in regards of real life adaptation! For those who haven't seen yet: general discussion about this can be found on gitter.im

**Comment by tolry** [comment]
ping @simpspector/owners

**Comment by DavidBadura** [comment]
rebased & ready @simpspector/owners

**Comment by dragonito** [comment]
to much changes +1 ;)

**Pull request merged**
