### PR TITLE
split badge and score calculator

### PR DESCRIPTION
**Pull request by DavidBadura**
developers can easily replace the score calculator

### CODE REVIEW

**Comment by DavidBadura** [comment]
@simpspector/owners ready :-)

**Comment by DavidBadura** [comment]
btw. i haven't changed the behavior

**Comment by larsborn** [comment]
I don't see all the implications this one has. Is it only to make it extendible? If I don't find the time to look into details, you can count me as +1 for merge.

**Comment by DavidBadura** [comment]
yes, and i moved view things like `score color` in the twig extension :wink:

**Comment by tolry** [comment]
:-1:

**Pull request merged**
