### PR TITLE
Cleanup with analyser

### PR DESCRIPTION
**Pull request by DavidBadura**
* remove docs in favor of https://github.com/simpspector/simpspector.github.io
* remove unused build scripts
* refactor GitCheckout into WorkspaceManager (name is more meaningful)
* use dependency injection from analyser (see https://github.com/simpspector/analyser/pull/38)
* added a new `simpspector:job:run` argument `id` to force a job start

### CODE REVIEW

**Comment by DavidBadura** [comment]
to have small pull request: ready :wink:

**Comment by tolry** [comment]
Could give a short description what you changed/cleaned up an why? I know, the code speaks for itself but still this would make reading and understanding the code changes much easier :smile:  Just a few notes would suffice.

**Comment by DavidBadura** [comment]
you're right. sorry. description was updated ;-)

**Comment by tolry** [comment]
thx, looks good :+1: for merge

**Comment by larsborn** [comment]
I only had a quick view at the code but assume, that you did a great job. So +1 from me.

**Pull request merged**
