### PR TITLE
update coc to version 1.2.0

### LINKED ISSUE #106: writing our own code of conduct
Having a code of conduct at all is a nice start, but since we are currently not 100% satisfied, we should probably phrase our own version.

If no one objects, I would take up the task. @simplethings/simpspector

### PR DESCRIPTION
**Pull request by tolry**
fixes #106

### CODE REVIEW

**Comment by DavidBadura** [comment]
:+1:

**Comment by tolry** [comment]
@smoench @larsborn @dragonito ?

**Comment by smoench** [comment]
:+1:

**Comment by larsborn** [comment]
I don't like this COC. So I'll let some else give the +1 ;)

**Pull request merged**
