### PR TITLE
Feature/fixtures

### PR DESCRIPTION
**Pull request by larsborn**

### CODE REVIEW

**Comment by larsborn** [comment]
will fix #99

**Comment by larsborn** [comment]
related to #100

**Comment by tolry** [comment]
Before you put to much work into collecting the actual fixtures data: @DavidBadura are there any significant schema changes in the pipeline that Lars should consider? I can't think of anything.

**Comment by tolry** [comment]
ping @DavidBadura

**Comment by tolry** [comment]
@larsborn should we mark this "na:check-still-relevant" or something like this? Since we David split the project into frontend and analyser, the setup of the separate components has become much easier. Therefore the need for fixtures to get started isn't that big anymore, imo. Another idea I had for this: we could provide a script which simulates a few webhook callbacks and let those run through the system. e.g. use the simpspector/simpspector repository

**Comment by DavidBadura** [comment]
That's the reason why I started the https://github.com/DavidBadura/git-webhooks lib.
To make it easier to process these events and simulate it :-)

The goal is to create a CLI command which you can fire webhook events.

**Comment by larsborn** [comment]
so we don't merge it and close it? Would be fine for me.

**Comment by tolry** [comment]
Always hard to throw away code, but in this case it might be wisest. Feel free to reopen if you like to.

**Comment by tolry** [comment]
@larsborn can we delete this branch?

**Pull request closed without merging**
